apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
  resources: ["*"]
  verbs:
  - "*"