apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.8.1
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: nodes
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /_cat/health
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cat/health
            port: 9200
          initialDelaySeconds: 60
          failureThreshold: 15
          timeoutSeconds: 10
          periodSeconds: 5
        # startupProbe:
        #   httpGet:
        #     path: /_cat/health
        #     port: 9200
        #   initialDelaySeconds: 60
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 10        
      volumes:
      - name: data
        hostPath:
          path: /mnt/data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: nodes
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elkaccess
  labels:
    service: elkaccess
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9200
      #nodePort: 31111
  selector:
    app: elasticsearch
