apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.8.1
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: nodes
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /_cat/health
            port: 9200
          #initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /_cat/health
            port: 9200
          #initialDelaySeconds: 60
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /_cat/health
            port: 9200
          initialDelaySeconds: 150
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10        
      volumes:
      - name: data
        hostPath:
          path: /mnt/data
          type: DirectoryOrCreate