apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.8.1
        ports:
        - containerPort: 5601
          name: webinterface
        livenessProbe:
          httpGet:
            path: /status
            port: 5601
          initialDelaySeconds: 200
          periodSeconds: 5
          failureThreshold: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 5601
          initialDelaySeconds: 200
          failureThreshold: 15
          timeoutSeconds: 10
          periodSeconds: 5
        # startupProbe:
        #   httpGet:
        #     path: /status
        #     port: 5601
        #   initialDelaySeconds: 90
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    service: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    name: webinterfaceport
    nodePort: 32222
  selector:
    app: kibana
