apiVersion: apps/v1
kind: Deployment 
metadata:
  name: apache-server-deployment 
  labels:
    app: webserver
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template: 
    metadata: 
      labels: 
        app: webserver
    spec: 
      containers: 
        - name: apache 
          image: httpd
          ports: 
            - containerPort: 80 
          volumeMounts: 
            - name: log 
              mountPath: /var/log/apache2 
      volumes: 
        - name: log 
          emptyDir: {}